export interface DashboardMetricMeta {
  description: string;
  calculation?: string;
  unit?: string;
  source?: string;
}

const FILTER_NOTE = "Updates with the active year, company, sector, geography, domain, implementation and amount filters.";

export const dashboardMetadata: Record<string, DashboardMetricMeta> = {
  "Total CSR Amount Spent for the Selected Period": { description: `Sum of reported project-level CSR amount spent across the current selection. ${FILTER_NOTE}`, calculation: "SUM(amountSpent)", unit: "₹ crore", source: "Project-level Amount Spent" },
  "Companies Reporting in the Selected Period": { description: `Distinct companies with at least one reported CSR project in the current selection. ${FILTER_NOTE}`, calculation: "COUNT DISTINCT(company)", unit: "companies", source: "Company Name" },
  "CSR Projects Reported in the Selected Period": { description: `Number of project records in the current selection. ${FILTER_NOTE}`, calculation: "COUNT(project rows)", unit: "projects", source: "Project records" },
  "Districts Reached by Reported CSR Projects": { description: `Distinct recorded districts represented by projects in the current selection; rows without a district are excluded. ${FILTER_NOTE}`, calculation: "COUNT DISTINCT(district)", unit: "districts", source: "District" },
  "Beneficiaries Reached by Reported CSR Projects": { description: `Sum of disclosed beneficiaries across selected projects; available only when the source includes this field. ${FILTER_NOTE}`, calculation: "SUM(beneficiaries)", unit: "people", source: "Beneficiaries" },
  "CSR Spend and Project Count by Financial Year": { description: `Annual total CSR amount spent and reported project count. ${FILTER_NOTE}`, calculation: "SUM(amountSpent) and COUNT(project rows), grouped by financial year", unit: "₹ crore and projects", source: "Financial Year, Amount Spent, Project records" },
  "States Ranked by Total CSR Spend": { description: `States ranked from highest to lowest aggregated CSR amount spent. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by state", unit: "₹ crore", source: "State, Amount Spent" },
  "Sectors Ranked by Total CSR Spend": { description: `BRSR sectors ranked by aggregated CSR amount spent; the displayed percentage is share of selected spend. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by BRSR sector", unit: "₹ crore and %", source: "BRSR Sector, Amount Spent" },
  "Companies Ranked by Total CSR Spend": { description: `Companies ranked by aggregated project-level CSR amount spent. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by company", unit: "₹ crore", source: "Company Name, Amount Spent" },
  "Geographic Distribution of Total CSR Spend by State": { description: `Map shading represents aggregated CSR amount spent for each recorded state. Pan-India and unspecified locations are not mapped. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by state", unit: "₹ crore", source: "State, Amount Spent" },
  "CSR Spend Share by BRSR Sector": { description: `Each slice shows a sector’s share of total CSR amount spent; smaller sectors may be grouped as remainder. ${FILTER_NOTE}`, calculation: "Sector SUM(amountSpent) ÷ selected SUM(amountSpent)", unit: "% of ₹ crore", source: "BRSR Sector, Amount Spent" },
  "Total CSR Spend by Sector and Financial Year": { description: `Tracks annual CSR amount spent for the six highest-spend sectors in the current selection. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by sector and financial year", unit: "₹ crore", source: "BRSR Sector, Financial Year, Amount Spent" },
  "Year-over-Year Change in CSR Spend by Sector": { description: "Compares each sector’s latest-year spend with the immediately preceding year. Sectors need at least ₹5 crore in the prior year; active filters apply.", calculation: "((latest spend − prior spend) ÷ prior spend) × 100", unit: "%", source: "Financial Year, BRSR Sector, Amount Spent" },
  "Schedule VII Thematic Areas by Total CSR Spend": { description: `Shows actual Schedule VII categories sized by total CSR spend. Hover values include amount, share of selected spend and reported project count. ${FILTER_NOTE}`, calculation: "SUM(amountSpent) and COUNT(project rows), grouped by Schedule VII category", unit: "₹ crore, %, projects", source: "Schedule VII Category, Amount Spent" },
  "Companies Ranked by Total CSR Spend in This View": { description: `Companies ranked by aggregated CSR amount spent within the current selection. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by company", unit: "₹ crore", source: "Company Name, Amount Spent" },
  "CSR Amount Spent by Company and Financial Year": { description: `Compares annual total CSR spend for selected companies. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by company and financial year", unit: "₹ crore", source: "Company Name, Financial Year, Amount Spent" },
  "Company Benchmark by Total CSR Spend": { description: "Compares selected companies using cumulative spend, projects and coverage under the active filters.", unit: "₹ crore, projects, states", source: "Company, Amount Spent, Project, State" },
  "Companies by BRSR Sector": { description: `Counts distinct reporting companies in each BRSR sector. ${FILTER_NOTE}`, calculation: "COUNT DISTINCT(company), grouped by BRSR sector", unit: "companies", source: "Company Name, BRSR Sector" },
  "CSR Spend by Schedule VII Thematic Area": { description: `Ranks Schedule VII categories by total CSR amount spent for the selected company or companies. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by Schedule VII category", unit: "₹ crore", source: "Schedule VII Category, Amount Spent" },
  "States Reached by Reported CSR Projects": { description: `Ranks states by selected-company CSR amount spent. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by state", unit: "₹ crore", source: "State, Amount Spent" },
  "Largest CSR Projects by Amount Spent": { description: `Lists project records with the highest disclosed CSR amount spent. ${FILTER_NOTE}`, calculation: "Project rows sorted by amountSpent descending", unit: "₹ crore", source: "Project, Amount Spent" },
  "State-wise Total CSR Spend": { description: `Shows aggregated project-level CSR amount spent by recorded state. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by state", unit: "₹ crore", source: "State, Amount Spent" },
  "Leading States: CSR Funding Profile": { description: `Compares leading states across their highest-spend Schedule VII categories. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by state and Schedule VII category", unit: "₹ crore", source: "State, Schedule VII Category, Amount Spent" },
  "Districts Ranked by Total CSR Spend": { description: `Districts ranked by aggregated CSR amount spent; rows without a recorded district are excluded. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by district", unit: "₹ crore", source: "District, Amount Spent" },
  "Latest Financial-Year CSR Spend": { description: `Total CSR spend in the latest financial year available within the active selection. ${FILTER_NOTE}`, calculation: "SUM(amountSpent) for latest selected year", unit: "₹ crore", source: "Financial Year, Amount Spent" },
  "Year-over-Year Change in CSR Spend": { description: "Percentage change in total CSR spend from the immediately preceding financial year to the latest year in the current selection.", calculation: "((latest spend − prior spend) ÷ prior spend) × 100", unit: "%", source: "Financial Year, Amount Spent" },
  "Compound Annual Growth Rate in CSR Spend": { description: "Annualized growth from the first to last financial year in the selected history. Requires at least two years and a positive starting value.", calculation: "((last spend ÷ first spend)^(1 ÷ intervals) − 1) × 100", unit: "%", source: "Financial Year, Amount Spent" },
  "Projected CSR Spend for the Next Financial Year": { description: "Illustrative next-year estimate produced from the historical spend trend; it is not a company forecast or commitment.", unit: "₹ crore", source: "Historical Financial Year and Amount Spent" },
  "CSR Spend by Financial Year with Projection": { description: "Shows historical annual CSR spend and the modelled projection band; active filters affect both the actual series and projection inputs.", unit: "₹ crore", source: "Financial Year, Amount Spent" },
  "Sectors with the Highest Year-over-Year CSR Spend Growth": { description: "Ranks sectors by latest year-over-year spend percentage increase. Requires at least ₹5 crore in the prior year.", unit: "%", source: "BRSR Sector, Financial Year, Amount Spent" },
  "Sectors with the Largest Year-over-Year CSR Spend Decline": { description: "Ranks sectors by latest year-over-year spend percentage decline. Requires at least ₹5 crore in the prior year.", unit: "%", source: "BRSR Sector, Financial Year, Amount Spent" },
  "Top Sectors by Total CSR Spend Across Financial Years": { description: "Annual spend trajectories for the six sectors with the highest cumulative CSR spend in the active selection.", unit: "₹ crore", source: "BRSR Sector, Financial Year, Amount Spent" },
  "Historical CSR Spend, Projects and Companies by Financial Year": { description: "Annual comparison table of total spend, year-over-year change, project records, distinct companies and mean spend per company.", unit: "₹ crore, %, counts", source: "Financial Year, Amount Spent, Project, Company" },
  "Total CSR Projects in the Selected Period": { description: `Count of project records in the current selection. ${FILTER_NOTE}`, unit: "projects", source: "Project records" },
  "Average CSR Spend per Project": { description: `Mean disclosed project amount, calculated as selected total spend divided by selected project records. ${FILTER_NOTE}`, unit: "₹ crore per project", source: "Amount Spent, Project records" },
  "CSR Spend in Aspirational Districts": { description: `Total CSR amount spent on rows mapped to designated aspirational districts. ${FILTER_NOTE}`, unit: "₹ crore and %", source: "District, Aspirational District flag, Amount Spent" },
  "Project Count by Disclosed CSR Spend Range": { description: `Counts projects in each disclosed spend band; clicking a bar applies that amount range as a filter. ${FILTER_NOTE}`, unit: "projects", source: "Amount Spent" },
  "Districts Ranked by Project-Level CSR Spend": { description: `Ranks recorded project locations by aggregated CSR amount spent. ${FILTER_NOTE}`, unit: "₹ crore", source: "District, Amount Spent" },
  "Filtered CSR Project Register": { description: "Project-level records matching the active filters. Columns show source values; sortable amount columns are in ₹ crore.", unit: "project records", source: "Filtered project dataset" },
  "Year-on-Year CSR Spend Outliers": { description: "Flags unusually large annual entity-level spend changes using standardized deviation from that entity’s historical movement.", unit: "₹ crore, %, z-score", source: "Historical entity-level Amount Spent" },
  "Company CSR Spend by Financial Year": { description: `Annual total CSR spend for the selected company. ${FILTER_NOTE}`, calculation: "SUM(amountSpent), grouped by financial year", unit: "₹ crore", source: "Company, Financial Year, Amount Spent" },
  "Company Profile": { description: "Reference details and reporting summary for the selected company, using the source company and sector fields." },
  "Sector Peers": { description: "Compares the selected company with other reporting companies in the same BRSR sector using total CSR spend under active filters.", unit: "₹ crore", source: "Company, BRSR Sector, Amount Spent" },
  "Projection Detail": { description: "Summarizes the modelled next-year spend estimate and its historical inputs. Projections are illustrative, not reported commitments.", unit: "₹ crore", source: "Historical Financial Year and Amount Spent" },
  "Suggested Actions": { description: "Rule-based analytical prompts derived from current spend concentration, growth and coverage patterns; not prescriptive advice." },
  "Data Quality": { description: "Reports missing or limited source fields that affect the interpretation of dashboard metrics and projections." },
  "Automated Data Insights": { description: "Rule-based findings generated from the current filtered dataset, such as concentration, growth and coverage patterns. Check each finding against the charts before quoting it.", source: "Current filtered CSR dataset" },
  "Natural Language Search": { description: "Answers questions against the currently loaded CSR dataset and active filter context; generated text should be checked against displayed metrics." },
  "Amount Spent Trajectory and Projection": { description: "Historical annual CSR spend with an illustrative next-year projection derived from the available trend.", unit: "₹ crore", source: "Financial Year, Amount Spent" },
  "Amount Spent Trajectory": { description: "Annual CSR amount spent for the selected company comparison, grouped by financial year.", unit: "₹ crore", source: "Company, Financial Year, Amount Spent" },
  "Implementation Channels by Total CSR Spend": { description: `Ranks modes of implementation by aggregated CSR amount spent. ${FILTER_NOTE}`, unit: "₹ crore", source: "Mode of Implementation, Amount Spent" },
  "Implementation Channels Summary": { description: `Summary of spend, projects and participating companies for each recorded implementation channel. ${FILTER_NOTE}`, unit: "₹ crore and counts", source: "Mode of Implementation, Amount Spent, Project, Company" },
  "Implementation Channel Presence by State": { description: `Shows geographic coverage of projects for the selected implementation channel. ${FILTER_NOTE}`, unit: "states and projects", source: "Mode of Implementation, State, Project" },
  "Schedule VII Focus Areas by Implementation Channel": { description: `Ranks Schedule VII categories funded through the selected implementation channels. ${FILTER_NOTE}`, unit: "₹ crore", source: "Mode of Implementation, Schedule VII Category, Amount Spent" },
  "Fastest-Growing States by CSR Spend": { description: "Ranks states by latest year-over-year CSR spend growth; only states meeting the minimum prior-year spend threshold are included.", unit: "%", source: "State, Financial Year, Amount Spent" },
  "Geographic Coverage Summary": { description: `Summarizes selected spend coverage across recorded states, districts and aspirational districts. ${FILTER_NOTE}`, unit: "counts and ₹ crore", source: "State, District, Aspirational flag, Amount Spent" },
  "Filtered Project Register": { description: "Project-level source records matching the active filters, with sortable financial year, company, location and spend fields.", unit: "project records and ₹ crore", source: "Filtered project dataset" },
  "National Rank by Total CSR Spend": { description: "Ranks the selected company against all companies by cumulative total CSR amount spent under the active period and filters.", unit: "rank and % share", source: "Company Name, Amount Spent" },
  "Latest-Year CSR Spend as a Share of Disclosed Obligation": { description: "Latest-year reported CSR spend divided by the company’s disclosed CSR obligation. Shown only when an obligation is available and comparable.", calculation: "latest-year spend ÷ disclosed obligation × 100", unit: "%", source: "Amount Spent, CSR Obligation" },
};

export function metricMeta(title: string): DashboardMetricMeta {
  const exact = dashboardMetadata[title];
  if (exact) return exact;
  const lower = title.toLowerCase();
  if (lower.includes("project")) return { description: `${title} uses project-level records matching the active dashboard filters.`, unit: lower.includes("spend") || lower.includes("largest") ? "projects and ₹ crore" : "projects", source: "Filtered project dataset" };
  if (lower.includes("state") || lower.includes("district") || lower.includes("coverage")) return { description: `${title} summarizes recorded geographic values for the active filters; unspecified locations are excluded where a named geography is required.`, unit: lower.includes("spend") ? "₹ crore" : "geographic counts", source: "State, District and project records" };
  if (lower.includes("sector") || lower.includes("theme") || lower.includes("focus")) return { description: `${title} groups the current filtered records by the named dataset category.`, unit: lower.includes("spend") || lower.includes("money") ? "₹ crore" : "counts", source: "BRSR Sector or Schedule VII Category" };
  if (lower.includes("spend") || lower.includes("amount") || lower.includes("fund")) return { description: `${title} is calculated from reported project-level CSR amounts and updates with active filters.`, unit: "₹ crore", source: "Amount Spent" };
  return { description: `${title} summarizes the currently loaded CSR dataset and respects the active dashboard filters where applicable.`, source: "Current filtered CSR dataset" };
}
