"use client";
import * as React from "react";

type User = { id: string; name: string; email: string; status: "pending" | "approved" | "rejected" | "inactive"; createdAt: string };
type Decision = "approved" | "rejected" | "inactive";
type Diagnostics = { authDataDir: string; usersFileExists: boolean; writable: boolean; separateVolume: boolean | null };

export default function AccessApprovalsPage() {
  const [users, setUsers] = React.useState<User[]>([]); const [error, setError] = React.useState(""); const [notice, setNotice] = React.useState(""); const [busy, setBusy] = React.useState(""); const [diagnostics, setDiagnostics] = React.useState<Diagnostics | null>(null);
  const load = React.useCallback(async () => { const response = await fetch("/api/admin/users", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to load accounts."); setUsers(body.users); setDiagnostics(body.diagnostics ?? null); }, []);
  React.useEffect(() => { load().catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load accounts.")); }, [load]);
  const review = async (id: string, status: Decision) => { setBusy(id); setError(""); setNotice(""); try { const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Update failed."); setNotice("Account status saved."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Update failed."); } finally { setBusy(""); } };
  const warnings = diagnostics ? [!diagnostics.writable ? `Account storage (${diagnostics.authDataDir}) is not writable.` : "", diagnostics.separateVolume === false ? `Account storage (${diagnostics.authDataDir}) is not on a persistent disk; registrations may be lost on redeploy.` : ""].filter(Boolean) : [];
  return <main style={{ padding: 32, maxWidth: 1050, margin: "0 auto" }}><div className="card"><div className="card-head"><div><h1 style={{ fontSize: 26 }}>User access</h1><p className="muted">Registered users sign in directly with their email and password. Administrators can deactivate or restore accounts here.</p></div></div>{warnings.map((warning) => <p key={warning} className="login-error">{warning}</p>)}{error ? <p className="login-error">{error}</p> : null}{notice ? <p className="login-help" role="status">{notice}</p> : null}<div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th align="left">User</th><th align="left">Registered</th><th align="left">Status</th><th align="right">Action</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} style={{ borderTop: "1px solid var(--border)" }}><td style={{ padding: "14px 8px" }}><strong>{user.name}</strong><br/><span style={{ color: "var(--text-soft)" }}>{user.email}</span></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td style={{ textTransform: "capitalize" }}>{user.status}</td><td align="right">{user.status !== "approved" ? <button disabled={busy === user.id} onClick={() => review(user.id, "approved")} style={{ marginRight: 8, padding: "8px 12px" }}>Restore access</button> : null}{user.status === "approved" ? <button disabled={busy === user.id} onClick={() => review(user.id, "inactive")} style={{ padding: "8px 12px" }}>Deactivate</button> : null}</td></tr>)}</tbody></table>{users.length === 0 ? <p>No registered users yet.</p> : null}</div></div></main>;
}
