"use client";
import * as React from "react";

type User = { id: string; name: string; email: string; status: "pending" | "approved" | "rejected" | "inactive"; createdAt: string; approvalEmailSentAt?: string };
type Decision = "approved" | "rejected" | "inactive";
type Diagnostics = { emailConfigured: boolean; adminNoticeConfigured: boolean; emailOtpRequired: boolean; authDataDir: string; usersFileExists: boolean; writable: boolean; separateVolume: boolean | null };
const emailNotice: Record<string, string> = {
  sent: "Saved. A notification email was sent to the user.",
  already_sent: "Saved. The approval email had already been sent, so no duplicate was sent.",
  failed: "Saved. The account is approved, but the notification email could not be delivered — check the server logs and email settings, then use “Resend email”.",
  not_configured: "Saved. The account is approved, but no email was sent because email delivery (RESEND_API_KEY / OTP_FROM_EMAIL) is not configured.",
};

export default function AccessApprovalsPage() {
  const [users, setUsers] = React.useState<User[]>([]); const [error, setError] = React.useState(""); const [notice, setNotice] = React.useState(""); const [busy, setBusy] = React.useState(""); const [diagnostics, setDiagnostics] = React.useState<Diagnostics | null>(null);
  const load = React.useCallback(async () => { const response = await fetch("/api/admin/users", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to load accounts."); setUsers(body.users); setDiagnostics(body.diagnostics ?? null); }, []);
  React.useEffect(() => { load().catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load accounts.")); }, [load]);
  const review = async (id: string, status: Decision) => { setBusy(id); setError(""); setNotice(""); try { const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Update failed."); setNotice(emailNotice[body.email] ?? "Saved."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Update failed."); } finally { setBusy(""); } };
  const warnings = diagnostics ? [
    !diagnostics.emailConfigured ? "Email delivery is not configured: approval emails and sign-in codes cannot be sent." : "",
    !diagnostics.writable ? `Account storage (${diagnostics.authDataDir}) is not writable.` : "",
    diagnostics.separateVolume === false ? `Account storage (${diagnostics.authDataDir}) is not on a separate persistent disk; approvals may be lost on restart or redeploy.` : "",
  ].filter(Boolean) : [];
  return <main style={{ padding: 32, maxWidth: 1050, margin: "0 auto" }}><div className="card"><div className="card-head"><div><h1 style={{ fontSize: 26 }}>Access approvals</h1><p className="muted">Approve or reject registered users. {diagnostics && !diagnostics.emailOtpRequired ? "Approved users sign in with their email and password." : "Approved users must verify an email OTP at every sign-in."}</p></div></div>{warnings.map((warning) => <p key={warning} className="login-error">{warning}</p>)}{error ? <p className="login-error">{error}</p> : null}{notice ? <p className="login-help" role="status">{notice}</p> : null}<div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th align="left">User</th><th align="left">Requested</th><th align="left">Status</th><th align="right">Action</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} style={{ borderTop: "1px solid var(--border)" }}><td style={{ padding: "14px 8px" }}><strong>{user.name}</strong><br/><span style={{ color: "var(--text-soft)" }}>{user.email}</span></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td style={{ textTransform: "capitalize" }}>{user.status}{user.status === "approved" && !user.approvalEmailSentAt ? <><br/><span style={{ color: "var(--text-soft)", textTransform: "none", fontSize: 12 }}>Approval email not sent</span></> : null}</td><td align="right">{user.status === "approved" && !user.approvalEmailSentAt ? <button disabled={busy === user.id} onClick={() => review(user.id, "approved")} style={{ marginRight: 8, padding: "8px 12px" }}>Resend email</button> : null}<button disabled={busy === user.id || user.status === "approved"} onClick={() => review(user.id, "approved")} style={{ marginRight: 8, padding: "8px 12px" }}>Approve</button><button disabled={busy === user.id || user.status === "rejected"} onClick={() => review(user.id, "rejected")} style={{ marginRight: user.status === "approved" ? 8 : 0, padding: "8px 12px" }}>Reject</button>{user.status === "approved" ? <button disabled={busy === user.id} onClick={() => review(user.id, "inactive")} style={{ padding: "8px 12px" }}>Deactivate</button> : null}</td></tr>)}</tbody></table>{users.length === 0 ? <p>No registrations yet.</p> : null}</div></div></main>;
}
