"use client";
import * as React from "react";

type User = { id: string; name: string; email: string; status: "pending" | "approved" | "rejected"; createdAt: string };
export default function AccessApprovalsPage() {
  const [users, setUsers] = React.useState<User[]>([]); const [error, setError] = React.useState(""); const [busy, setBusy] = React.useState("");
  const load = React.useCallback(async () => { const response = await fetch("/api/admin/users"); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to load accounts."); setUsers(body.users); }, []);
  React.useEffect(() => { load().catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load accounts.")); }, [load]);
  const review = async (id: string, status: "approved" | "rejected") => { setBusy(id); setError(""); try { const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Update failed."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Update failed."); } finally { setBusy(""); } };
  return <main style={{ padding: 32, maxWidth: 1050, margin: "0 auto" }}><div className="card"><div className="card-head"><div><h1 style={{ fontSize: 26 }}>Access approvals</h1><p className="muted">Approve or reject registered users. Approved users must verify an email OTP at every sign-in.</p></div></div>{error ? <p className="login-error">{error}</p> : null}<div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th align="left">User</th><th align="left">Requested</th><th align="left">Status</th><th align="right">Action</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} style={{ borderTop: "1px solid var(--border)" }}><td style={{ padding: "14px 8px" }}><strong>{user.name}</strong><br/><span style={{ color: "var(--text-soft)" }}>{user.email}</span></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td style={{ textTransform: "capitalize" }}>{user.status}</td><td align="right"><button disabled={busy === user.id || user.status === "approved"} onClick={() => review(user.id, "approved")} style={{ marginRight: 8, padding: "8px 12px" }}>Approve</button><button disabled={busy === user.id || user.status === "rejected"} onClick={() => review(user.id, "rejected")} style={{ padding: "8px 12px" }}>Reject</button></td></tr>)}</tbody></table>{users.length === 0 ? <p>No registrations yet.</p> : null}</div></div></main>;
}
